### ISSUE TITLE
Question about White Elephant and M/R

### ISSUE THREAD

**Issue by pbj0001** [LinkedInAttic/white-elephant#7]
Is it correct that the White Elephant log uploader only works with M/R 1 and not Yarn, since statsupload.pl appears to look only in the local file system?  I believe Yarn stores the history files in HDFS already.

Can White Elephant as it is currently implemented handle Yarn logs already in HDFS?

**Comment by matthayes** [comment]
I haven't tested White Elephant against Yarn log files yet.  So not sure if it can handle the log files stored directly in HDFS.
