### ISSUE TITLE
white-elephant rocks!

### ISSUE THREAD

**Issue by dronamk** [LinkedInAttic/white-elephant#8]
- This is not an issue. just a comment Thanking the contributors matthayes et al; *

I did'nt know how to reach you guys, This is an "excellent" project. Got the log collection/processing/presentation to work like a charm. The project is a super-success. Thanks to you we're able to monitor usage about various clusters now. I tried this myself with persistence to mysql by latching on to JT process and found the solution was not quite scalable. You guys are amazing! Thanks again. @dronamk.

**Comment by matthayes** [comment]
Thanks for the feedback and really glad you're finding it useful!

By the way I just created a discussion group to make communication easier (link now also in README):

http://groups.google.com/group/linkedin-white-elephant
