### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by syedarifbadsha80** [LinkedInAttic/white-elephant#9]
Hi,

I downloaded the zip file and tried to build in my ubuntu box, followed the steps, but my build failed with below error:-
setup:
     [exec] Making sure RVM is not installed (since incompatible with rbenv)
     [exec] [v] done
     [exec] Checking for rbenv
     [exec] rbenv is not installed
     [exec] Installing rbenv
     [exec] [v] Created temporary directory
     [exec] [v] Found git
     [exec] fatal: unable to connect to github.com:
     [exec] github.com[0: 204.232.175.90]: errno=Connection refused
     [exec]
     [exec] [x] Failed to find git
     [exec] script will exit

In the setup file 
function cloneRbEnv() {
  tmp_dir=`mktemp -d tmp.XXXXXXXX`
  checkErrors "Failed to create temp directory" "Created temporary directory"
  command -v git >/dev/null 2>&1
  checkErrors "Failed to find git" "Found git"
  rbenv_dir=$base_dir/.rbenv
  git clone -q git://github.com/linkedin/rbenv.git $tmp_dir && mv $tmp_dir $rbenv_dir
}

the git path was pointing to the author sstephen and i modifed it to linked in, still no luck.

Need help on this.

**Comment by matthayes** [comment]
Hmm the error message indicates your machine couldn't reach github.com.  Is this a persistent problem?  Can you think of why this would be?

**Comment by syedarifbadsha80** [comment]
Yes Hayes, i am new to things, resolved it, this was due to the proxy
problem.
i am using ubutu, But i still have a issue....

://
maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.jar
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: org.apache.avro#avro;1.7.2: not found
[ivy:resolve]           :: org.apache.avro#avro-mapred;1.7.2: not found
[ivy:resolve]           :: org.apache.avro#avro-compiler;1.7.2: not found
[ivy:resolve]           :: org.testng#testng;6.0.1: not found
[ivy:resolve]           :: commons-logging#commons-logging;1.1.1: not found
[ivy:resolve]           :: log4j#log4j;1.2.17: not found
[ivy:resolve]           :: org.slf4j#slf4j-log4j12;1.6.4: not found
[ivy:resolve]           :: joda-time#joda-time;1.6: not found
[ivy:resolve]           :: com.googlecode.json-simple#json-simple;1.1.1:
not found
[ivy:resolve]           :: org.json#json;20090211: not found
[ivy:resolve]           :: com.google.guava#guava;13.0.1: not found
[ivy:resolve]           :: org.easymock#easymock;3.1: not found
[ivy:resolve]           :: org.apache.hadoop#hadoop-core;1.0.4: not found
[ivy:resolve]           :: org.apache.hadoop#hadoop-tools;1.0.4: not found
[ivy:resolve]           :: com.hadoop.gplcompression#hadoop-lzo;0.4.15: not
found
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by matthayes** [comment]
No worries.  It looks like what you pasted is somewhat incomplete.  Can you include more of the log?  Basically what happens here is it downloads JARs from various maven repositories and it seems it's not finding them, or can't reach the repo.

**Comment by syedarifbadsha80** [comment]
Please see the logs:--

[ivy:resolve]
http://maven.twttr.com/org/apache/avro/avro-compiler/1.7.2/avro-compiler-1.7.2.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/testng/testng/6.0.1/testng-6.0.1.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/testng/testng/6.0.1/testng-6.0.1.jar
[ivy:resolve]           module not found: org.testng#testng;6.0.1
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/testng/testng/6.0.1/testng-6.0.1.pom
[ivy:resolve]     -- artifact org.testng#testng;6.0.1!testng.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/testng/testng/6.0.1/testng-6.0.1.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/testng/testng/6.0.1/testng-6.0.1.pom
[ivy:resolve]     -- artifact org.testng#testng;6.0.1!testng.jar:
[ivy:resolve]
http://maven.twttr.com/org/testng/testng/6.0.1/testng-6.0.1.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ivy:resolve]           module not found:
commons-logging#commons-logging;1.1.1
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[ivy:resolve]     -- artifact
commons-logging#commons-logging;1.1.1!commons-logging.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[ivy:resolve]     -- artifact
commons-logging#commons-logging;1.1.1!commons-logging.jar:
[ivy:resolve]
http://maven.twttr.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ivy:resolve]           module not found: log4j#log4j;1.2.17
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
[ivy:resolve]     -- artifact log4j#log4j;1.2.17!log4j.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]     http://maven.twttr.com/log4j/log4j/1.2.17/log4j-1.2.17.pom
[ivy:resolve]     -- artifact log4j#log4j;1.2.17!log4j.jar:
[ivy:resolve]     http://maven.twttr.com/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.jar
[ivy:resolve]           module not found: org.slf4j#slf4j-log4j12;1.6.4
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.pom
[ivy:resolve]     -- artifact
org.slf4j#slf4j-log4j12;1.6.4!slf4j-log4j12.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.pom
[ivy:resolve]     -- artifact
org.slf4j#slf4j-log4j12;1.6.4!slf4j-log4j12.jar:
[ivy:resolve]
http://maven.twttr.com/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.jar
[ivy:resolve]           module not found: joda-time#joda-time;1.6
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.pom
[ivy:resolve]     -- artifact joda-time#joda-time;1.6!joda-time.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/joda-time/joda-time/1.6/joda-time-1.6.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/joda-time/joda-time/1.6/joda-time-1.6.pom
[ivy:resolve]     -- artifact joda-time#joda-time;1.6!joda-time.jar:
[ivy:resolve]
http://maven.twttr.com/joda-time/joda-time/1.6/joda-time-1.6.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
[ivy:resolve]           module not found:
com.googlecode.json-simple#json-simple;1.1.1
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
[ivy:resolve]     -- artifact
com.googlecode.json-simple#json-simple;1.1.1!json-simple.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
[ivy:resolve]     -- artifact
com.googlecode.json-simple#json-simple;1.1.1!json-simple.jar:
[ivy:resolve]
http://maven.twttr.com/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.jar
[ivy:resolve]           module not found: org.json#json;20090211
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.pom
[ivy:resolve]     -- artifact org.json#json;20090211!json.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/json/json/20090211/json-20090211.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/json/json/20090211/json-20090211.pom
[ivy:resolve]     -- artifact org.json#json;20090211!json.jar:
[ivy:resolve]
http://maven.twttr.com/org/json/json/20090211/json-20090211.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/google/guava/guava/13.0.1/guava-13.0.1.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/google/guava/guava/13.0.1/guava-13.0.1.jar
[ivy:resolve]           module not found: com.google.guava#guava;13.0.1
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/com/google/guava/guava/13.0.1/guava-13.0.1.pom
[ivy:resolve]     -- artifact com.google.guava#guava;13.0.1!guava.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/com/google/guava/guava/13.0.1/guava-13.0.1.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/com/google/guava/guava/13.0.1/guava-13.0.1.pom
[ivy:resolve]     -- artifact com.google.guava#guava;13.0.1!guava.jar:
[ivy:resolve]
http://maven.twttr.com/com/google/guava/guava/13.0.1/guava-13.0.1.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/easymock/easymock/3.1/easymock-3.1.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/easymock/easymock/3.1/easymock-3.1.jar
[ivy:resolve]           module not found: org.easymock#easymock;3.1
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/easymock/easymock/3.1/easymock-3.1.pom
[ivy:resolve]     -- artifact org.easymock#easymock;3.1!easymock.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/easymock/easymock/3.1/easymock-3.1.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/easymock/easymock/3.1/easymock-3.1.pom
[ivy:resolve]     -- artifact org.easymock#easymock;3.1!easymock.jar:
[ivy:resolve]
http://maven.twttr.com/org/easymock/easymock/3.1/easymock-3.1.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.jar
[ivy:resolve]           module not found:
org.apache.hadoop#hadoop-core;1.0.4
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.pom
[ivy:resolve]     -- artifact
org.apache.hadoop#hadoop-core;1.0.4!hadoop-core.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.pom
[ivy:resolve]     -- artifact
org.apache.hadoop#hadoop-core;1.0.4!hadoop-core.jar:
[ivy:resolve]
http://maven.twttr.com/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.jar
[ivy:resolve]           module not found:
org.apache.hadoop#hadoop-tools;1.0.4
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.pom
[ivy:resolve]     -- artifact
org.apache.hadoop#hadoop-tools;1.0.4!hadoop-tools.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.pom
[ivy:resolve]     -- artifact
org.apache.hadoop#hadoop-tools;1.0.4!hadoop-tools.jar:
[ivy:resolve]
http://maven.twttr.com/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.jar
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.pom
[ivy:resolve]   Host repo1.maven.org not found. url=
http://repo1.maven.org/maven2/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.jar
[ivy:resolve]           module not found:
com.hadoop.gplcompression#hadoop-lzo;0.4.15
[ivy:resolve]   ==== ibiblio: tried
[ivy:resolve]
http://repo1.maven.org/maven2/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.pom
[ivy:resolve]     -- artifact
com.hadoop.gplcompression#hadoop-lzo;0.4.15!hadoop-lzo.jar:
[ivy:resolve]
http://repo1.maven.org/maven2/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.jar
[ivy:resolve]   ==== twttr.com: tried
[ivy:resolve]
http://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.pom
[ivy:resolve]     -- artifact
com.hadoop.gplcompression#hadoop-lzo;0.4.15!hadoop-lzo.jar:
[ivy:resolve]
http://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.jar
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: org.apache.avro#avro;1.7.2: not found
[ivy:resolve]           :: org.apache.avro#avro-mapred;1.7.2: not found
[ivy:resolve]           :: org.apache.avro#avro-compiler;1.7.2: not found
[ivy:resolve]           :: org.testng#testng;6.0.1: not found
[ivy:resolve]           :: commons-logging#commons-logging;1.1.1: not found
[ivy:resolve]           :: log4j#log4j;1.2.17: not found
[ivy:resolve]           :: org.slf4j#slf4j-log4j12;1.6.4: not found
[ivy:resolve]           :: joda-time#joda-time;1.6: not found
[ivy:resolve]           :: com.googlecode.json-simple#json-simple;1.1.1:
not found
[ivy:resolve]           :: org.json#json;20090211: not found
[ivy:resolve]           :: com.google.guava#guava;13.0.1: not found
[ivy:resolve]           :: org.easymock#easymock;3.1: not found
[ivy:resolve]           :: org.apache.hadoop#hadoop-core;1.0.4: not found
[ivy:resolve]           :: org.apache.hadoop#hadoop-tools;1.0.4: not found
[ivy:resolve]           :: com.hadoop.gplcompression#hadoop-lzo;0.4.15: not
found
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] :::: ERRORS
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro/1.7.2/avro-1.7.2.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro/1.7.2/avro-1.7.2.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro-mapred/1.7.2/avro-mapred-1.7.2.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro-mapred/1.7.2/avro-mapred-1.7.2.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro-compiler/1.7.2/avro-compiler-1.7.2.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/avro/avro-compiler/1.7.2/avro-compiler-1.7.2.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/testng/testng/6.0.1/testng-6.0.1.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/testng/testng/6.0.1/testng-6.0.1.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/log4j/log4j/1.2.17/log4j-1.2.17.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/joda-time/joda-time/1.6/joda-time-1.6.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/joda-time/joda-time/1.6/joda-time-1.6.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/json/json/20090211/json-20090211.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/json/json/20090211/json-20090211.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/google/guava/guava/13.0.1/guava-13.0.1.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/google/guava/guava/13.0.1/guava-13.0.1.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/easymock/easymock/3.1/easymock-3.1.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/easymock/easymock/3.1/easymock-3.1.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/hadoop/hadoop-core/1.0.4/hadoop-core-1.0.4.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/org/apache/hadoop/hadoop-tools/1.0.4/hadoop-tools-1.0.4.jar
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.pom
[ivy:resolve]   Server access Error: Connection refused url=
http://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.15/hadoop-lzo-0.4.15.jar
[ivy:resolve]
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
/home/bigdata/Install/white-elephant-master/server/build.xml:110: The
following error occurred while executing this line:
/home/bigdata/Install/white-elephant-master/hadoop/build.xml:53: impossible
to resolve dependencies:
        resolve failed - see output for details

Total time: 44 seconds

**Comment by matthayes** [comment]
Are you sure you solved the proxy issues?  It is still saying it cannot
resolve repo1.maven.org or maven.twttr.com.

**Comment by syedarifbadsha80** [comment]
I had set http_proxy variable and the initial error were gone..... and now
stuck here.... .

**Comment by matthayes** [comment]
What happens when you try "ping repo1.maven.org" or "ping maven.twttr.com"?

**Comment by syedarifbadsha80** [comment]
ping: unknown host repo1.maven.org

**Comment by matthayes** [comment]
As far as I can tell this is an environment issue.  If you can't ping repo1.maven.org even then it's not going to work.  I suggest either digging into why you can't ping this host or building on another machine.  You could build a WAR on another machine which has access to the external hosts and then deploy it to tomcat on the machine which will host it.

**Comment by ashokbee** [comment]
I am getting this.. error
[exec] [x] Failed to find git

The machine where I am trying to build this does not have internet access.
What are my options?
I see that Matthayes says , I can build this war file and take it there.
Did anyone built this way?
Appreciate your help.
Thanks
Bashok

**Comment by ashokbee** [comment]
Needs to build on a machine which doesnot have any internet connection. 
Is there any documented for that deployment.
Thanks in advance.
Bashok

**Comment by matthayes** [comment]
Sorry it isn't possible to build it without an internet connection and there isn't any documentation on how to do this.
